version: '3.8'

services:
  auth-service:
    build:
      context: ../RRSolucoesFinanceiraAuth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MySqlConnection=Server=auth-db;Database=authdb;User=root;Password=root;
      - RabbitMq=amqp://guest:guest@rabbitmq:5672;
    networks:
      - app-network
    depends_on:
      - auth-db
      - rabbitmq

  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - app-network
    volumes:
      - auth_data:/var/lib/mysql

  gateway-service:
    build:
      context: ../RRSolucoesFinanceiraApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network
    depends_on:
      - auth-service

  user-service:
    build:
      context: ../RRSolucoesFinanceiraUsers
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MySqlConnection=Server=users-db;Database=userdb;User=root;Password=root;
      - RabbitMq=amqp://guest:guest@rabbitmq:5672;
    networks:
      - app-network
    depends_on:
      - users-db
      - rabbitmq

  users-db:
    image: mysql:8
    container_name: users-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      - app-network
    volumes:
      - users_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

networks:
  app-network:
    driver: bridge
  
volumes:
  auth_data:
  users_data: